cass0:
    image: abh1nav/cassandra:latest
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7199:7199"

cass-node:
    image: abh1nav/cassandra:latest
    links:
      -  cass0:seed
    environment:
      - SEED=seed
